### ISSUE TITLE
BROKEN

### ISSUE THREAD

**Issue by ElectroGamesDev** [but3k4/youtube-views#1]
I did youtube.py 10 https://www.youtube.com/watch?v=H53BgIIaHd0&t=23s then it said

`C:\Users\Tristyn\Desktop>youtube.py 10 https://www.youtube.com/watch?v=H53BgIIaHd0&t=23s
usage: youtube.py [--visits VISITS] [--url URL] [-v] [-h]
youtube.py: error: unrecognized arguments: 10 https://www.youtube.com/watch?v=H53BgIIaHd0
't' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by pyperanger** [comment]
RTFM 
Remove &t=23s 

try: python youtube.py --visits 10 --url https://www.youtub...

**Comment by but3k4** [comment]
It is not broken. You did not use the cli properly.
