### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by derekmaclingster** [but3k4/youtube-views#5]
1) there is not Folder called "YouTube"
2) latest python 
3) installed requirements.txt 
AND STILL:

> Traceback (most recent call last):
>   File "C:\Users\work\PY\youtube-views-master\bot.py", line 9, in <module>
>     from modules.youtube import youtube
>   File "C:\Users\work\PY\youtube-views-master\modules\youtube.py", line 10, in <module>
>     from selenium import webdriver
> ImportError: No module named selenium
>

**Comment by but3k4** [comment]
Sorry, but, you did not install all dependencies, the message is clear: **No module named selenium**. Here is the **requirements.txt**:

requests>=2.22.0
selenium==3.141.0
urllib3>=1.25.8

In addition, **YouTube** is not a folder, it is a class, it's part of youtube.py. Another thing: I do not use Windows, so, I suggest you to try to spin up a Linux VM or a container, you can use the Windows Subsystem for Linux or VirtualBox or docker.
